### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by chrystianfarias** [Sorackb/sinesp-api#154]
Any plate queried returns the not found (404) error. Sinesp-api still works today?

```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>

undefined:1
<html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at request (C:\Users\Farias\Projetos\sharkbot\node_modules\sinesp-api\index.js:80:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async get (C:\Users\Farias\Projetos\sharkbot\test.js:4:19)
 ```
 
 ```js
 const sinespApi = require('sinesp-api');

const get = async () => {
    let vehicle = await sinespApi.search('GHX2G27');
    console.log(vehicle);
}
get();
```

**Comment by rhanything** [comment]
Same issue here

> Any plate queried returns the not found (404) error. Sinesp-api still works today?
> 
> ```
> <html>
> <head><title>404 Not Found</title></head>
> <body bgcolor="white">
> <center><h1>404 Not Found</h1></center>
> <hr><center>nginx/1.14.1</center>
> </body>
> </html>
> 
> undefined:1
> <html>
> ^
> 
> SyntaxError: Unexpected token < in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at request (C:\Users\Farias\Projetos\sharkbot\node_modules\sinesp-api\index.js:80:21)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async get (C:\Users\Farias\Projetos\sharkbot\test.js:4:19)
> ```
> 
> ```js
> const sinespApi = require('sinesp-api');
> 
> const get = async () => {
>    let vehicle = await sinespApi.search('GHX2G27');
>    console.log(vehicle);
> }
> get();
> ```

**Comment by fabmont** [comment]
I'm not sure exactly where this lib is retrieving the plate data, but a lot of barriers popped up.
I know that the official API from Sinesp was updated and now it requires auth through the SSO by gov.br.

I have a PR opened on [BrasilAPI](https://github.com/BrasilAPI/BrasilAPI/pull/163) repo to implement plate search that are paused in the moment due those challenges. If you guys wanna take a look, it would be great to centralize all the inputs and thoughts that we could bring up.

**Comment by GuiiSantos** [comment]
Sinesp-api still works today?

> fabmont
